# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/BlockProt" # Location of package manifests
    schedule:
      interval: "weekly" # We will just check for updates every week.
      day: "monday" # Monday is the default
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/SPlugin" # Location of package manifests
    schedule:
      interval: "weekly" # We will just check for updates every week.
      day: "monday" # Monday is the default
