# SPlugin Config

# in features you can enable/disable various features from this plugin.
features:
  afk: true # Enable AFK displaying when players are inactive for 2 minutes
  chatFormat: true # Enables the formatting of chat messages

chatFormat:
  format: "§7[player] > §r[message]"
  discordFormat: "§9[user] > §r[message]"

# If you provide a token, the bot will accept commands for the server.
# If you provide at least one guild and channel combination, the server will stream all
# discord activity to the server and vice versa.
discord:
  token: null # Your discord bot token
  channels:
    # GUILD_ID: CHANNEL_ID
    # You can have 1 channel per guild.
    # You can define multiple combinations to stream to multiple channels in multiple guilds.
  joinMessage: false # Whether or not to send a message to discord when a player joins the server.
  leaveMessage: false # Whether or not to send a message to discord when a player leaves the server.

messages:
  join:
    - "§a[player] has joined the server!" # §a is light green
  leave:
    - "§6[player] has left the server!" # §6 is dark yellow
  death:
    - "[message]..."
  welcome:
    - "Welcome [player]!"
  welcomeBack:
    - "Welcome back, [player]!"
  afk:
    - "[player] §eis now AFK" # §e is color coding for yellow
  not_afk:
    - "[player] §eis no more AFK."
